### ISSUE TITLE
Inconsistency in `get_*_var_names` between type hint and docstring.

### ISSUE THREAD

**Issue by BSchilperoort** [csdms/bmi-python#36]
In the `get_*_var_names` methods, the type hint is `tuple[str]`, however the docstrings state:

> """**List** of a model's output variables.

and:

> **list of str**

So which one should it be?

**Comment by mdpiper** [comment]
Tuple is correct.

I wonder if there's a use case for a mutable return from these functions? I think I prefer having them immutable.

**Comment by BSchilperoort** [comment]
I think the return should be immutable, but the docstring stated the type should be a list. I've created #37 to correct this.
