### ISSUE TITLE
Mistake in type hints for tuples

### ISSUE THREAD

**Issue by BSchilperoort** [csdms/bmi-python#38]
The type hints of the `Bmi` class have a couple of return types as `tuple[str]`. For example: 

https://github.com/csdms/bmi-python/blob/793f5661c75f252775d250f9b7556a00214003ff/src/bmipy/bmi.py#L106

However, in python's typing system this means _a tuple containing a single string_. For a tuple of strings the correct type hint is:

```python
    def get_input_var_names(self) -> tuple[str, ...]: 
```

To quote the [Python documentation on this](https://docs.python.org/3/library/typing.html#typing.Tuple):

> To denote a tuple which could be of any length, and in which all elements are of the same type T, use tuple[T, ...].

**Comment by mdpiper** [comment]
@BSchilperoort Thank you for catching this. I learned something new about type hints!

**Comment by mdpiper** [comment]
Fixed with #37.
