### ISSUE TITLE
set_value argument name: src or values

### ISSUE THREAD

**Issue by visr** [csdms/bmi-python#6]
I just noticed in

https://github.com/csdms/bmi-python/blob/0fcca448d097bc001f7492094ce1fd95d041b81d/bmipy/bmi.py#L394-L407

That the argument name `values` does not match the `src` in the docstring and the `src` on the [BMI website](https://bmi.readthedocs.io/en/latest/#set-value).

Since in Python these are not strictly positional but can be addressed as keyword arguments as well, I didn't just want to change it.

**Comment by mdpiper** [comment]
@visr It should be `src`, to match [bmi.sidl](https://github.com/csdms/bmi/blob/master/bmi.sidl). Thanks for spotting this error!

**Comment by mdpiper** [comment]
Fixed with 17d7d72.

**Comment by visr** [comment]
Ok thanks! I assumed it should be `src`. What I meant was that 17d7d72bb1e21dd5135fc0b60c44313da7710496 breaks code of people that used keyword agument syntax like `set_value(name="myname", values=np.zeros(3))` as opposed to `set_value("myname", np.zeros(3))`, since `values` is now not an argument name anymore. Not sure if that is an issue in practice though, you can probably judge that better.

For your information, the main reason I was carefully reading it was because I used it as a basis for https://github.com/Deltares/BasicModelInterface.jl. Not sure to which extent you would be interested in a Julia BMI specification next to the C, C++, Fortran and Python ones. As I mention in the readme it probably still needs some implementations to prove itself. But perhaps it's good you are aware of its existence. If you'd want to adopt it eventually I'd be happy to transfer the repo to the CSDMS org.

**Comment by mcflugen** [comment]
@visr This is great! @ethan-pierce is also working with BMI for Julia. I believe his repository is private at the moment but you two should compare notes sometime.

**Comment by visr** [comment]
Great, thanks for letting me know. @ethan-pierce, feel free to create an issue on the BasicModelInterface.jl repository to discuss anything, or if you prefer you can drop me an email as well. I didn't register BasicModelInterface.jl as a package yet, so we could also go with what you worked on.
